apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master0
  namespace: redis
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeMode: Filesystem
  hostPath:
    path: "/data/data-master0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas0
  namespace: redis
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeMode: Filesystem
  hostPath:
    path: "/data/data-replicas0"
